local player = require("game.player")
local M = {}

function M.run()
    require("game.tests.input_routing").run()
    require("game.tests.main_menu_ui").run()
    require("game.tests.menu_scene").run()
    require("game.tests.run_setup_ui").run()

    local actor = player.new()
    player.update(actor, 1, { right = true })
    assert(actor.x == 232 and actor.y == 90)
    player.update(actor, 10, { left = true, up = true })
    assert(actor.x == 5 and actor.y == 5)
    require("game.tests.hwatu").run()
    require("game.tests.run").run()
    require("game.tests.card_ui").run()
    require("game.tests.hand_ui").run()
    require("game.tests.gwang_slots_ui").run()
    require("game.tests.scoreboard_ui").run()
    require("game.tests.action_buttons_ui").run()
    require("game.tests.scoring_pipeline").run()
    require("game.tests.shop_engine").run()
    require("game.tests.shop_purchases").run()
    require("game.tests.packs").run()
    require("game.tests.pack_ui").run()
    require("game.tests.shop_ui").run()
    require("game.tests.blind_select_ui").run()
    require("game.tests.play_integration").run()
    require("game.tests.score_anim_ui").run()
    require("game.tests.card_effects").run()
    require("game.tests.tags").run()
    require("game.tests.boss_blinds").run()
    require("game.tests.vouchers").run()
    require("game.tests.wish_cards").run()
    require("game.tests.tarots").run()
    require("game.tests.economy").run()
    require("game.tests.deck").run()
    require("game.tests.gwang_catalog").run()
    require("game.tests.rng").run()
    require("game.tests.seed_ui").run()
    require("game.tests.run_history").run()
    require("game.tests.blind_targets").run()
    require("game.tests.blind_flow").run()
    require("game.tests.round_engine").run()
    require("game.tests.run_rules").run()
    require("game.tests.consumables_ui").run()
    require("game.tests.tarot_target_ui").run()
    require("game.tests.tarot_use_flow").run()
    print("GOSTRO_UNIT_OK")
end

return M
