local scoreboard = require("game.ui.scoreboard")
local score_icon_art = require("game.ui.score_icon_art")
local action_buttons = require("game.ui.action_buttons")

local function write_capture(canvas, path)
    local encoded = canvas:newImageData():encode("png")
    local file = assert(io.open(path, "wb"))
    file:write(encoded:getString())
    file:close()
end

function love.load()
    require("game.qa.offscreen_window").minimizeWindow(320, 180)
    love.graphics.setDefaultFilter("nearest", "nearest")
    love.graphics.setFont(love.graphics.newFont("assets/fonts/Galmuri11.ttf", 8))

    local canvas = love.graphics.newCanvas(320, 180)
    canvas:setFilter("nearest", "nearest")
    love.graphics.setCanvas(canvas)
    love.graphics.clear(0.025, 0.035, 0.08, 1)
    local state = scoreboard.new()
    scoreboard.set_target(state, 300)
    scoreboard.set_hand_result(state, 42, 3)
    scoreboard.draw(state)
    score_icon_art.draw_money(278, 84, 12)
    love.graphics.setColor(0.3, 1, 0.4, 1)
    love.graphics.print("$17", 292, 86)
    score_icon_art.draw_deck(278, 100, 12)
    love.graphics.setColor(1, 1, 1, 1)
    love.graphics.print("34", 292, 102)
    score_icon_art.draw_discard(278, 116, 12)
    love.graphics.setColor(1, 1, 1, 1)
    love.graphics.print("3", 292, 118)
    score_icon_art.draw_hand(278, 132, 12)
    love.graphics.setColor(1, 1, 1, 1)
    love.graphics.print("4", 292, 134)
    local buttons = action_buttons.new(4, 3)
    action_buttons.set_selection(buttons, 2)
    action_buttons.draw(buttons)
    love.graphics.setCanvas()

    local output = assert(os.getenv("SCORE_ICON_QA_OUTPUT"), "SCORE_ICON_QA_OUTPUT is required")
    write_capture(canvas, output)
    print("SCORE_ICON_LOVE_QA_OK 320x180 " .. output)
    love.event.quit(0)
end
