-- game/tests/play_integration.lua
-- Integration tests for play scene state machine.
-- Headless: no love.graphics required.

local M = {}

function M.run()
    local play = require("game.scenes.play")
    local run  = require("game.run")
    local hwatu = require("game.hwatu")

    -- (1) new scene starts in blind_select state
    local scene = play.new()
    assert(scene.state == "blind_select", "initial state must be blind_select")
    assert(scene.run_state ~= nil, "must have run_state")
    assert(scene.run_state.ante == 1, "ante starts at 1")

    -- (2) select_blind transitions to a deterministic finite round.
    local old_random = math.random
    math.random = function() error("play path must not use math.random") end
    play.select_blind(scene, 1) -- small blind
    math.random = old_random
    assert(scene.state == "playing", "after blind select -> playing")
    assert(scene.run_state.blind == "small", "blind must be small")
    assert(scene.run_state.deck and #scene.run_state.deck.cards == 40,
        "default New Run config installs the finite hwatu deck")
    assert(scene.round ~= nil, "playing owns a finite round engine")
    assert(#scene.round.hand == 8 and #scene.round.draw_pile == 32,
        "round deals 8 from the finite 40-card deck")
    assert(scene.hand ~= nil, "must have hand UI state")
    assert(scene.scoreboard ~= nil, "must have scoreboard")
    assert(scene.buttons ~= nil, "must have action buttons")
    assert(scene.buttons.hands_left == scene.round.hands_left
        and scene.buttons.discards_left == scene.round.discards_left,
        "action buttons mirror round engine resources")

    -- (3) play_hand evaluates cards and adds score via engine
    -- Deal some cards and play them
    assert(#scene.hand.cards == 8, "must deal 8 cards")
    -- Select first card and play
    local hand_ui = require("game.ui.hand")
    local buttons_ui = require("game.ui.action_buttons")
    hand_ui.select(scene.hand, 1)
    hand_ui.select(scene.hand, 2)
    hand_ui.select(scene.hand, 3)
    buttons_ui.set_selection(scene.buttons, #scene.hand.selected_order)
    local ok = play.play_hand(scene)
    assert(ok, "play_hand must succeed with selection")
    assert(scene.run_state.round_score > 0, "score must increase after play")
    assert(scene.round.hands_left == 3 and scene.buttons.hands_left == 3,
        "round engine owns and UI mirrors consumed hands")
    assert(#scene.round.hand == 8, "finite round refills the hand")
    assert(#scene.round.hand + #scene.round.draw_pile + #scene.round.discard_pile == 40,
        "play conserves the finite deck")

    -- (4) play enough to clear blind, then auto-transition to shop
    -- Force score high enough to clear
    local target = run.blind_target(scene.run_state)
    while scene.run_state.round_score < target do
        run.add_score(scene.run_state, target)
    end
    play.check_clear(scene)
    assert(scene.state == "shop", "score >= target -> shop")
    assert(scene.shop ~= nil, "must have shop state")
    assert(scene.shop.run_state == scene.run_state and #scene.shop.random_offers == 3,
        "live shop is generated by shop_engine against the run state")

    -- Shop rerolls use the seeded engine and consume tag effects on run state.
    scene.run_state.tags.free_rerolls = 1
    local before_reroll_money = scene.run_state.money
    local rerolled, paid = play.reroll_shop(scene)
    assert(rerolled and paid == 0, "free-reroll tag applies on the live shop path")
    assert(scene.run_state.money == before_reroll_money
        and scene.run_state.tags.free_rerolls == 0,
        "live reroll keeps engine money synchronized and consumes the tag")

    -- Random-offer purchases are also transacted by shop_engine.
    local offer = scene.shop.random_offers[1]
    offer.kind, offer.identity, offer.price, offer.sold = "gwang", "chips", 0, false
    assert(play.buy_shop_card(scene, 1), "live random offer can be purchased")
    assert(offer.sold and scene.run_state.gwang[1].identity == "chips",
        "purchase marks the engine slot sold and applies it to the run")

    -- (5) leave_shop transitions to blind_select for next blind
    play.leave_shop(scene)
    assert(scene.state == "blind_select", "after shop -> blind_select")
    assert(scene.run_state.blind == "big", "next blind is big")
    assert(scene.blind_select.current == "big", "blind UI follows the engine's next blind")
    assert(scene.blind_select.blinds[2].available == true
        and scene.blind_select.blinds[1].available == false
        and scene.blind_select.blinds[3].available == false,
        "blind UI cannot replay small or jump ahead to boss")
    assert(scene.run_state.phase == "play", "run phase is play")

    -- (6) discard_hand works
    play.select_blind(scene, 2) -- big blind
    assert(scene.state == "playing")
    hand_ui.select(scene.hand, 1)
    buttons_ui.set_selection(scene.buttons, #scene.hand.selected_order)
    local discard_ok = play.discard_hand(scene)
    assert(discard_ok, "discard must succeed with selection")

    -- (7) full ante cycle: small->big->boss->next ante
    local scene2 = play.new()
    for _, blind_idx in ipairs({1, 2, 3}) do
        assert(scene2.state == "blind_select")
        play.select_blind(scene2, blind_idx)
        assert(scene2.state == "playing")
        -- Force clear
        local t = run.blind_target(scene2.run_state)
        run.add_score(scene2.run_state, t)
        play.check_clear(scene2)
        assert(scene2.state == "shop")
        play.leave_shop(scene2)
    end
    assert(scene2.run_state.ante == 2, "after 3 blinds -> ante 2")
    assert(scene2.run_state.blind == "small", "back to small")

    -- (8) gwang slots sync from run state
    assert(scene2.gwang_slots ~= nil, "must have gwang_slots UI")

    -- (9) The final unsuccessful hand ends the run instead of stalling.
    local losing = play.new("LOSE-PATH")
    play.select_blind(losing, 1)
    losing.round.hands_left = 1
    losing.round.target = math.huge
    losing.buttons.hands_left = 1
    hand_ui.select(losing.hand, 1)
    buttons_ui.set_selection(losing.buttons, 1)
    assert(play.play_hand(losing), "final hand can be played")
    assert(losing.state == "lost" and losing.run_state.phase == "lost",
        "hands exhausted below target transitions to a recorded loss")

    print("  play_integration: OK")
end

return M
